
sudo: true

language: ruby
rvm:
  - 2.5.1

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      install:
        - sudo update-alternative --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_script:
        -# sudo mv /usr/bin/gcc /usr/bin/gcc.old
        #- sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
        - eval "${MATRIX_EVAL}"
        - gem build agoo.gemspec
        - gem install oj
        - gem install agoo-*
        - cd ext/agoo
        - ruby extconf.rb && make clean all
        - cd ../..
    - os: osx
      before_script:
        - eval "${MATRIX_EVAL}"
        - gem build agoo.gemspec
        - gem install oj
        - gem install agoo-*
        - cd ext/agoo
        - ruby extconf.rb && make clean all
        - cd ../..

script:
  - cd test
  - ./log_test.rb
  - ./base_handler_test.rb
  - ./rack_handler_test.rb
  # - ./static_test.rb
