language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

os:
  - linux
  - osx

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_script:
  - if [ ${TRAVIS_OS_NAME} == "osx" ] ; then brew install openssl ; fi
  - sudo mv /usr/bin/gcc /usr/bin/gcc.old
  - sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - eval "${MATRIX_EVAL}"
  - gem build agoo.gemspec
  - gem install oj
  - gem install agoo-*
  - cd ext/agoo
  - ruby extconf.rb && make clean all
  - cd ../..

script:
  - cd test
  - ./log_test.rb
  - ./base_handler_test.rb
  - ./rack_handler_test.rb
  # - ./bind_test.rb
  # - ./static_test.rb
  # - ./graphql_test.rb
  # - ./hijack_test.rb
